name: Publish HttpClient Nuget Package
on:
  push:
    tags:
    - HttpClient/v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-nupkg:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Restore
      run: |
        dotnet nuget remove source "github.com/${{ github.repository_owner }}"
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text \
          --name "github.com/${{ github.repository_owner }}" "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        dotnet restore ./Shizou.HttpClient/Shizou.HttpClient.csproj
    - name: Package
      run: |
        version=$(grep -Eqo '[0-9]+\.[0-9]+\.[0-9]+[0-9A-Za-z.-]*' <<< "$GITHUB_REF_NAME") &&
        dotnet pack ./Shizou.HttpClient/Shizou.HttpClient.csproj --no-restore -c Release "-p:Version=${version}" "-p:Authors=${{ github.repository_owner }}" \
          "-p:RepositoryUrl=${{ github.repositoryUrl }}" "-p:PackageProjectUrl=${{ github.server_url }}/${{ github.repository }}"
    - name: Push
      run: dotnet nuget push Shizou.HttpClient/bin/Release/Shizou.HttpClient.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
        --source "github.com/${{ github.repository_owner }}"
