name: publish-http-client.yml
on:
  push:
    tags:
    - HttpClient/v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-nupkg:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Package
      run: >
        dotnet nuget add source --username ${{ github.repository_owner }} --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text 
        --name github "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json"
        && dotnet pack RHashWrapper/RHashWrapper.csproj -p:GeneratePackageOnBuild=false
        && version=$(grep -Eo '[0-9]+\.[0-9]+\.[0-9]+[0-9A-Za-z.-]*' <<< "$GITHUB_REF_NAME" | head -1)
        && dotnet pack ./Shizou.HttpClient/Shizou.HttpClient.csproj -c Release "-p:Version=${version}" "-p:Authors=${{ github.repository_owner }}"
        "-p:RepositoryUrl=${{ github.repositoryUrl }}" "-p:PackageProjectUrl=${{ github.server_url }}/${{ github.repository }}"
        && dotnet nuget push "bin/Release/Shizou.HttpClient/Shizou.HttpClient.${version}.nupkg" --source github
