name: Publish HttpClient Nuget Package
on:
  push:
    tags:
    - HttpClient/v[0-9]+.[0-9]+.[0-9]+

jobs:
  publish-nupkg:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
    - name: Add Source Credential
      run: |
        dotnet nuget remove source "github.com/$GITHUB_REPOSITORY_OWNER"
        dotnet nuget add source --username $GITHUB_REPOSITORY_OWNER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text \
          --name "github.com/$GITHUB_REPOSITORY_OWNER" "https://nuget.pkg.github.com/$GITHUB_REPOSITORY_OWNER/index.json"
    - name: Package
      run: |
        version=$(grep -Eqo '[0-9]+\.[0-9]+\.[0-9]+[0-9A-Za-z.-]*' <<< "$GITHUB_REF_NAME") &&
        dotnet pack Shizou.HttpClient/Shizou.HttpClient.csproj -c Release "-p:Version=${version}" "-p:Authors=$GITHUB_REPOSITORY_OWNER" \
          "-p:RepositoryUrl=${{ github.repositoryUrl }}" "-p:PackageProjectUrl=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY"
    - name: Push
      run: dotnet nuget push Shizou.HttpClient/bin/Release/Shizou.HttpClient.*.nupkg --api-key ${{ secrets.GITHUB_TOKEN }}
        --source "github.com/$GITHUB_REPOSITORY_OWNER"
